export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const GET_USER_POSTS_REQUEST = "GET_USER_POSTS_REQUEST";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_FAIL = "GET_USER_POSTS_FAIL";

export const GET_USER_REPLIES_REQUEST = "GET_USER_REPLIES_REQUEST";
export const GET_USER_REPLIES_SUCCESS = "GET_USER_REPLIES_SUCCESS";
export const GET_USER_REPLIES_FAIL = "GET_USER_REPLIES_FAIL";

export const GET_POSTS_RESET = "GET_POSTS_RESET";

export const GET_USER_PINNED_POSTS_SUCCESS = "GET_USER_PINNED_POSTS_SUCCESS";
export const GET_USER_PINNED_POSTS_FAIL = "GET_USER_PINNED_POSTS_FAIL";

export const TOGGLE_USERS_MODE = "TOGGLE_USERS_MODE";
export const TOGGLE_POSTS_MODE = "TOGGLE_POSTS_MODE";

export const GET_SEARCH_USERS_SUCCESS = "GET_SEARCH_USERS_SUCCESS";
export const GET_SEARCH_USERS_FAIL = "GET_SEARCH_USERS_FAIL";
export const GET_SEARCH_USERS_RESET = "GET_SEARCH_USERS_RESET";

export const GET_POST_RESET = "GET_POST_RESET";
export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_RESET = "GET_PROFILE_RESET";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const ADD_REPLY = "ADD_REPLY";

export const TOGGLE_MODAL = "TOGGLE_MODAL";

export const TOGGLE_POST_LIKE_SUCCESS = "TOGGLE_POST_LIKE_SUCCESS";
export const TOGGLE_POST_LIKE_FAIL = "TOGGLE_POST_LIKE_FAIL";

export const TOGGLE_POST_RETWEET_SUCCESS = "TOGGLE_POST_RETWEET_SUCCESS";
export const TOGGLE_POST_RETWEET_FAIL = "TOGGLE_POST_RETWEET_FAIL";

export const POST_PIN_SUCCESS = "POST_PIN_SUCCESS";
export const POST_PIN_FAIL = "POST_PIN_FAIL";

export const POST_UNPIN_SUCCESS = "POST_UNPIN_SUCCESS";
export const POST_UNPIN_FAIL = "POST_UNPIN_FAIL";

export const GET_USER_FOLLOWING_SUCCESS = "GET_USER_FOLLOWING_SUCCESS";
export const GET_USER_FOLLOWING_FAIL = "GET_USER_FOLLOWING_FAIL";
export const GET_USER_FOLLOWING_REQUEST = "GET_USER_FOLLOWING_REQUEST";

export const GET_USER_FOLLOWERS_SUCCESS = "GET_USER_FOLLOWERS_SUCCESS";
export const GET_USER_FOLLOWERS_FAIL = "GET_USER_FOLLOWERS_FAIL";
export const GET_USER_FOLLOWERS_REQUEST = "GET_USER_FOLLOWERS_REQUEST";

// export const GET_USER_FOLLOWING_SUCCESS = "GET_USER_FOLLOWING_SUCCESS";
// export const GET_USER_FOLLOWING_FAIL = "GET_USER_FOLLOWING_FAIL";

export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL";

export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS";
export const CREATE_GROUP_CHAT_FAIL = "CREATE_GROUP_CHAT_FAIL";

export const GET_CHATS_REQUEST = "GET_CHATS_REQUEST";
export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
export const GET_CHATS_FAIL = "GET_CHATS_FAIL";

export const GET_CHAT_REQUEST = "GET_CHAT_REQUEST";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAIL = "GET_CHAT_FAIL";
export const GET_CHAT_RESET = "GET_CHAT_RESET";

export const UPDATE_CHATNAME_SUCCESS = "UPDATE_CHATNAME_SUCCESS";
export const UPDATE_CHATNAME_FAIL = "UPDATE_CHATNAME_FAIL";

export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";

export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";

export const SETUP_SOCKET = "SETUP_SOCKET";
export const SHOW_INDICATOR = "SHOW_INDICATOR";
export const HIDE_INDICATOR = "HIDE_INDICATOR";
